<?php

// This file was automatically generated by readMetadata.php
// Don't edit!

$metadataIDProviders = array (
  'https://idp.cafmoz.morenet.ac.mz/idp/shibboleth' => 
  array (
    'SSO' => 'https://idp.cafmoz.morenet.ac.mz/idp/profile/SAML2/Redirect/SSO',
    'Name' => 'CAFMOZ IDP',
    'en' => 
    array (
      'Name' => 'CAFMOZ IDP',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol',
    '' => 
    array (
      'Keywords' => 'https://idp.cafmoz.morenet.ac.mz/idp/shibboleth morenet.ac.mz',
    ),
  ),
)
?>