<?php

// This file was automatically generated by readMetadata.php
// Don't edit!

$metadataSProviders = array (
  'https://filesender.morenet.ac.mz/shibboleth' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://filesender.morenet.ac.mz/Shibboleth.sso/Login',
    ),
    'Name' => 'https://filesender.morenet.ac.mz/shibboleth',
    'ACURL' => 
    array (
      0 => 'https://filesender.morenet.ac.mz/Shibboleth.sso/SAML2/POST',
      1 => 'https://filesender.morenet.ac.mz/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://filesender.morenet.ac.mz/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://filesender.morenet.ac.mz/Shibboleth.sso/SAML2/ECP',
    ),
    'Protocols' => 'urn:oasis:names:tc:SAML:2.0:protocol',
    'Contacts' => 
    array (
    ),
  ),
)
?>